### ISSUE TITLE
Brainstorming datasets/topics

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/Mental-Health-in-Tech-Dashboard#1]
Hi team 👋 

Let's use this issue to pour out ideas about the potential dataset and topic that we will use for this project.

**Comment by mikelynch416** [comment]
I found this dataset for our meeting tommorow which shows the power generated by solar panels at a solar plant in India at 15 minute intervals.
https://www.kaggle.com/anikannal/solar-power-generation-data
 
**Here is an example writeup of how we could use this dataset for the project:**

Our role: Data scientist consultancy firm

Target audience: Solar Power Plant operators

It is important for solar power plant operators to understand the state of their equipment both for safety and operational reasons (ex. to identify deficient equipment before it causes further problems, to identify when the configuration of equipment can be improved to generate more power, etc.). Having an easy way to visualize the state of the solar panels thus is an opportunity to improve the safety and efficiency of operations at the power plant.

To address this challenge, we propose building a data visualization dashboard that would allow power plant administrators to visually explore the yield of each solar panel in the plant as well as see metrics on the plant's overall performance like the total yield of all the solar panels. For an example usage, operators could use the dashboard to monitor how much power is being generated by each solar panel and identify if a panel needs maintenance based on its yield (ex. if a solar panel is generating much less power than average it probably needs maintenance).

**Comment by d-sel** [comment]
Dataset: http://archive.ics.uci.edu/ml/datasets/Beijing+Multi-Site+Air-Quality+Data#
Topic: Air Quality (this dataset contains data points from the city of Beijing)

I think this dataset can be geared towards different audiences. One example:
Our role: government or environmental organization
Target audience: general public or internal use

It has been shown that air quality can affect people's health and time spent in poor air quality conditions should generally be minimized. For the public entity to better advise the public as well as potentially look at solutions for dealing with polluting industries, a dashboard of air quality across the city can provide monitoring to see if any changes need to be made in real-time.

The proposed dashboard can show regional air quality as well as filter for specific areas which contain more detailed data. The data can also be specified for a certain metric and trends can be viewed based on time of the day, month of the year or by year.

**Comment by chiragrank** [comment]
Those are nice suggestions! I found an interesting WORLD HAPPINESS DATA based Gallup world poll at [Kaggle](https://www.kaggle.com/unsdsn/world-happiness)

The data is divided over 5 years from 2015 to 2019. The dashboard can be created to understand the contribution of factors like Family, Health, Freedom, Government trust, the country's economy in the calculation of Happiness scores for different countries. Information can be helpful in the policy-making of government and non-government organizations as the target audience.

**Comment by fatse** [comment]
I briefly looked into the datasets and dataset resources that Joel has provided in the milestone 1 document and I really liked the one that is related to the [mental health of tech people](https://www.kaggle.com/osmi/mental-health-in-tech-survey). I would like to explore more that data set and see different insights one can get, for example, are people who are self-employed in better mental health condition than the people who work in a corporate, or will it help if the company provides wellness programs, are the employees happier?

I think that there are some useful features in that dataset that we can leverage to create some nice visualizations and interactions in the dashboard.
