### ISSUE TITLE
Confirming PR Process

### ISSUE THREAD

**Issue by d-sel** [UBC-MDS/Mental-Health-in-Tech-Dashboard#16]
Hi @chiragrank @mikelynch416 @fatse ,
I would like to clarify process for approving PRs. We only need one person to approve even though all three are requested to review - is that correct?

Thanks,
Selma

**Comment by chiragrank** [comment]
Yes, you are right. I think we discussed that a minimum of one approval would be required.  So it can be merged right away if the approver feels confident of the changes. If the approver feels more consensus would be better for that pull request, it can wait for other approvals. Having the requirement of one approval would help us to speed up things and not making a hard rule can help us get more opinion whenever possible. Would be helpful to get inputs from others as well on this.

**Comment by d-sel** [comment]
Finished discussion in meeting 21/01/21.
