### ISSUE TITLE
Milestone 2 - Reflection

### ISSUE THREAD

**Issue by mikelynch416** [UBC-MDS/Mental-Health-in-Tech-Dashboard#31]
In this section, your group should document on what you have implemented in your dashboard so far and explain what is not yet implemented. It is important that you include what you know is not working in your dashboard, so that your TAs can distinguish between features in development and bugs.

Reflect on what you think your dashboard does well what its limitations are, and what are good future improvements and additions. This section should not be more than 500 words and the reflection-milestone2.md document should live in your GitHub.com repo in the doc folder.

**Comment by mikelynch416** [comment]
# What we have implemented so far

As we mentioned in our proposal document, we wanted to make the “Mental Health in Tech Workers” app in such a way that it could provide an overview of the survey data used for the app but also include additional information relevant to our target audience. So far we have included these two sections in our app. Right now, the overview section consists of a visualization that allows the user to select a question from the survey and quickly visualize the responses and the HR questions section includes plots that each answer a specific question HR domain experts may have about the ways mental health issues affect work productivity as well as the factors which affect the rate at which productivity issues are experienced. In addition to these plots we have also implemented filters that allow users to filter the data included in the visualizations according to factors like the age and sex of survey respondents so that they can make the visualizations more closely align with the factors that exist in their workplaces (for example, with the current filters an HR domain expert could tune the visualizations to be more relevant to their predominantly male and older workforce).

# Future improvements

For our future improvements, we would still like to include additional visualizations relevant to HR policies and how they affect mental health. For example, in our proposal's usage scenario section we indicated that we would like to be able to visualize the responses to the survey question “Does your employer provide resources to learn more about mental health issues and how to seek help?” as well as to visualize how certain other variables correlate with the occurences of survey responses indicating high levels of impact on worker productivity due to mental health issues. This would allow users to answer questions like "Does the data indicate that my proposed policy of (for example) expanding remote working options is likely to lead to a decrease in the rate of workers experiencing  mental health issues that impact their work productivity?".

Additonally, we would like to continue to add filters based on the survey response data so that HR domain experts can accurately model the conditions that exist in their workplaces as well as gain intuition on the potential effects of proposed policies.

A final priority will be to apply some styling to the app since in its current state it is not very visually appealing, which could impact the user experience.

# Known Issues

- Question names in overview section
- filters are not currently applied to all visualizations in the HR Questions section
- Visualization functions not currently adhereing to DRY principles

**Comment by d-sel** [comment]
A few notes:
- I think we may have issues incorporating plots relating to productivity because I believe that `productivity` had a lot of missing values. You may want to include a section on things we've opted not to proceed with.
- a future improvement: global filtering - I believe we do not have this yet.
- I noted the following as future things we may want to consider adding:
  - benefits dropdown
  - second tab
  - cleaning up 'Null' responses (converting them to show as a different value in the plots)

**Comment by chiragrank** [comment]
Looks good!
The last pull request works on points 1 and 2 in the known issues but they might still hold true to keep in the reflection.

**Comment by mikelynch416** [comment]
# What we have implemented so far

As we mentioned in our proposal document, we wanted to make the “Mental Health in Tech Workers” app in such a way that it could provide an overview of the survey data used for the app but also include additional information relevant to our target audience. So far we have included these two sections in our app. Right now, the overview section consists of a visualization that allows the user to select a question from the survey and quickly visualize the responses and the HR questions section includes plots that each answer a specific question HR domain experts may have about the ways mental health issues affect work productivity as well as the factors which affect the rate at which productivity issues are experienced. In addition to these plots we have also implemented filters that allow users to filter the data included in the visualizations according to factors like the age and sex of survey respondents so that they can make the visualizations more closely align with the factors that exist in their workplaces (for example, with the current filters an HR domain expert could tune the visualizations to be more relevant to their predominantly male and older workforce).

# Future improvements

For our future improvements, we would still like to include additional visualizations relevant to HR policies and how they affect mental health. For example, in our proposal's usage scenario section we indicated that we would like to be able to visualize the responses to the survey question “Does your employer provide resources to learn more about mental health issues and how to seek help?” as well as to visualize how certain other variables correlate with the occurences of survey responses indicating high levels of impact on worker productivity due to mental health issues. This would allow users to answer questions like "Does the data indicate that my proposed policy of (for example) expanding remote working options is likely to lead to a decrease in the rate of workers experiencing  mental health issues that impact their work productivity?".

Additonally, we would like to continue to add filters based on the survey response data (ex. filters for the benefits that are available at each of the survey respondents' companies) and make sure they apply to a global dataset which all visualizations could use so that HR domain experts can accurately model the conditions that exist in their workplaces as well as gain intuition on the potential effects of proposed policies.

Also, in our proposal we mentioned that we would like our dashboard to be tabbed but right now there is only a single page with sections so another future improvement would be to change over to tabbed sections. A final priority will be to apply some styling to the app since in its current state it is not very visually appealing, which could impact the user experience.  

# Known Issues

- Question names in overview section don't directly correspond to survey questions due to size constraints in the dropdown widget
- Visualization functions not currently adhereing to DRY principles so there could be potential for performance improvements by sharing functions and data between visualizations
- Some visualizations have null values showing up since they use data which has not yet been fully cleaned

**Comment by fatse** [comment]
@mikelynch416 Looks great, good job!

Regarding the "Known issues" section, specifically this one:
> Question names in overview section don't directly correspond to survey questions due to size constraints in the dropdown widget

I think it would be more appropriate if we worded it a bit differently because the questions actually do correspond to the survey question (option values and the data) but we just reworded them.

Maybe something like the example below looks more concise to what we did:
> In the overview section the labels of the dropdown options have been reworded from the original survey questions due to size constraints in the dropdown widget
