### ISSUE TITLE
Include gif screenshot/cast

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/Mental-Health-in-Tech-Dashboard#52]
Hey everyone! Could I ask that you include a screenshot/cast of your entire dashboard in the repo as a gif image/video? I would need this to create a nice thumbnail for you in the gallery I am making, now I am just getting your wireframe. I took a screenshot and converted it to a gif for you, so if you want you can just save this file in the repo root, but I think yours would be great with a short screencast since you have the different tabs.

![mental-health-dashboard](https://user-images.githubusercontent.com/4560057/107132327-ca17bf80-6892-11eb-8954-01e271637561.gif)

**Comment by fatse** [comment]
Hi @joelostblom,

Thank you very much for taking the time to take a screenshot for us.
We planned to add a GIF of our app for sure, but we're still working on some cosmetic enhancements and polishing the app further. When we're done with that, before the deadline that is, we'll add a GIF to our repo's README and remove the wireframes. 

We appreciate your effort and your dedication.

Skål!

**Comment by joelostblom** [comment]
Hahaha  "skål"!! :laughing: In Swedish we only use it for for clinking glasses together when drinking, so it sounds like your group is having a fun Saturday! Skål to you too! =D

The rest sounds great too!

**Comment by joelostblom** [comment]
Nice screencast everyone and great call on the vertical donut charts :+1:  Closing this.
